# Generated by Django 5.2.6 on 2025-10-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(choices=[('homework', 'Study and Homework help'), ('language', 'Language learning'), ('career', 'Career Advancment'), ('skill', 'Skill Development'), ('exam', 'Exam Preparation'), ('other', 'Other')], default='other', max_length=60)),
                ('grade_level', models.CharField(choices=[('elementary', 'Elementary (kG-5)'), ('primary', 'Primary (6-8)'), ('secondary', 'High School (9-12)'), ('college', 'College/University'), ('adult', 'Adult Learner'), ('professional', 'professional Development')], default='primary', max_length=60)),
                ('favorite', models.CharField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('teaching_prefrence', models.CharField(default='both', max_length=60)),
                ('subjects', models.TextField()),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=15, null=True)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='id_cards/')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='verification_docs/')),
                ('horuly_rate', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
