# Generated by Django 5.2.6 on 2025-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='language',
            field=models.TextField(),
        ),
    ]
