# Generated by Django 5.2.6 on 2025-11-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_user_alter_tutorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
