# Generated by Django 5.2.6 on 2025-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentprofile_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
