# Generated by Django 5.2.6 on 2025-10-12 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField()),
                ('total_session', models.PositiveIntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_payed', models.BooleanField(default=False)),
                ('session_duration', models.PositiveIntegerField(default=45)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remaining_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('denied', 'Request Not Accepted'), ('canceld', 'Canceld'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('remaining_sessions', models.IntegerField()),
                ('current_start_time', models.DateTimeField(blank=True, null=True)),
                ('current_end_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Reschedule')], default='scheduled', max_length=15)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('offline', 'In_person')])),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('notification_status', models.CharField(choices=[('0', 'not_notified'), ('1', 'notified_morning'), ('2', 'notified_hour'), ('3', 'notified')], default='0', max_length=15)),
                ('base_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor_sessions.basesession')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_calss', to='tutor_sessions.bookedsession')),
            ],
        ),
    ]
