# Generated by Django 5.2.6 on 2025-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Accepted'), ('ongoing', 'Ongoing'), ('decline', 'Request Not Accepted'), ('canceld', 'Canceld'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
