# Generated by Django 5.2.6 on 2025-11-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availablity', '0001_initial'),
        ('tutor_sessions', '0002_alter_basesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesession',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='availablity.tutorpackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Reschedule'), ('completed', 'completed'), ('up_comming', 'Up Comming')], default='scheduled', max_length=15),
        ),
    ]
